Removed .bzr contents from juju-charm, since that is only used for Launchpad. Finalized Juju charm for Metis 1.4.5, featuring the use of git for installing and updating Metis.

diff --git a/juju-charm/metis/hooks/install b/juju-charm/metis/hooks/install
--- a/juju-charm/metis/hooks/install
+++ b/juju-charm/metis/hooks/install
@@ -1,11 +1,13 @@
 #!/bin/bash
-set -e # If any command fails, stop execution.
+set -ex # If any command fails, stop execution.
+
+USER=$(whoami)
 
 installMetis(){ #Function to pull and install Metis
 	# Clone the git repository
 	echo "Cloning Metis git repository (stable branch). No worries, it is a perfect clone."
 	mkdir -p /tmp/metis # Create a temporary directory to work in
-	git clone --branch master git@github.com:StroblIndustries/Metis.git /tmp/metis # Clone the repo to /tmp/metis
+	git clone --branch master https://github.com/StroblIndustries/Metis.git /tmp/metis # Clone the repo to /tmp/metis
 
 	cd /tmp/metis/
 
@@ -13,7 +15,7 @@ installMetis(){ #Function to pull and install Metis
 
 	echo "We're removing some unnecessary stuff. It's like unstuffing a teddy bear."
 
-	for content in ${unnecessaryContent[@]} # Recurse over array
+	for content in "${unnecessaryContent[@]}" # Recurse over array
 	do
 		rm -rf "$content" # Remove the individual item(s)
 	done
@@ -25,7 +27,13 @@ installMetis(){ #Function to pull and install Metis
 	chmod -R 1777 /var/www/ # Force 777 permissions
 }
 
-apt-get install -y git # Ensure necessary git dependency exist.
+gitAlreadyInstalled=$(dpkg --get-selections git | grep -c 'install')
+
+if [ ! $gitAlreadyInstalled -eq 1 ]; then # If git is NOT installed
+	apt-get install -y git # Ensure necessary git dependency exist.
+	git config --global user.email "noneofyour@business.com"
+	git config --global user.name "Anonymous"
+fi
 
 # Check for existing installs
 echo "Our detectives are on the case. Checking for an existing Metis install."
@@ -47,6 +55,14 @@ if [ -f /var/www/Metis/metis.php ]; then #If Metis is already installed
 	echo "Metis is done updating \o/ Mission accomplished."
 else #If Metis is NOT already installed
 	echo "Found no Metis install. The construction crew has arrived and we're installing Metis now."
+
+	# SSH Key Checking (Required for Git)
+	echo "Checking for an SSH key. Security reasons yo."
+	
+	if [ ! -f "/home/$USER/.ssh/id_rsa.pub" ]; then # If an SSH key does NOT exist
+		mkdir -p /home/root/.ssh
+		ssh-keygen -t rsa -N "metis" -C "metis-git-key" -f "/home/$USER/.ssh/id_rsa"
+	fi
 
 	# Dependency Checking (No sense in re-installing dependencies)
 
